# Generated by Django 2.0 on 2020-03-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_price', models.FloatField(default=0)),
                ('order', models.FloatField(default=0)),
                ('car_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_abbv', models.CharField(max_length=10)),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_car', to='Models.Car')),
                ('nxt_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nxt_car', to='Models.Car')),
                ('prev_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_car', to='Models.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abbv', models.CharField(max_length=10)),
                ('type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_abbv', models.CharField(max_length=10)),
                ('color_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='Models.CarBrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_color', to='Models.Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='Models.CarType'),
        ),
    ]
