# Generated by Django 2.0 on 2020-03-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='type_description',
            field=models.CharField(max_length=50),
        ),
    ]
