# Generated by Django 2.0 on 2020-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20200308_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='order',
            field=models.FloatField(default=0, null=True),
        ),
    ]
