# Generated by Django 2.0 on 2020-03-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_auto_20200308_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='node_car',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='nxt_car',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='prev_car',
        ),
        migrations.DeleteModel(
            name='CarList',
        ),
    ]
